### ISSUE TITLE
Compiler error with 4D 20.4

### ISSUE THREAD

**Issue by pol-itworx** [vdelachaux/SVG-with-Classes#10]
Hello,

I tried to use some of your classes, mainly xml and svg.
When it comes to compile with v 20.4 I've an error with '...', as above.
**Function newRef($root : Text; $nameSpace : Text;  ...  : Text) : cs.xml**
Seems to be okay with R6.
I don't know what it is, I mean '...', could you light me up?

Merci !

**Comment by vdelachaux** [comment]
"…" design variadic parameters (all other parameters after the last declared).
A remplacement of parameter indirection syntax ${N}.

doc: https://developer.4d.com/docs/Concepts/parameters/#parameter-indirection-n
